### PR TITLE
created mygarden structure

### LINKED ISSUE #55: Client - Implement MyGarden View

### PR DESCRIPTION
**Pull request by yassinej**
closes #55 
Created a structure that follows provided mockup.
What do you think guys?

### CODE REVIEW

**Comment by jaduh** [comment]
Nice work on the structure. Image links seem to be broken. I would add some margin to the feature-phrase. And some margin-left to the logo of the navbar.

**Comment by yassinej** [comment]
@jaduh What links are you talking about? 
foe the landing page structure you can commit the desired changed or send me the values desired for the argin

**Comment by jaduh** [comment]
The images won't display. I will add margins tonight or tomorow!

**Comment by yassinej** [comment]
I'm merging this. for all minor changes. we can create tasks later.

**Pull request merged**
