### PR TITLE
Server - Connect DB #27: Needs a lot more work

### PR DESCRIPTION
**Pull request by HixOba**

### CODE REVIEW

**Review by yassinej — CHANGES_REQUESTED** [review]
As discussed the task was to simply connect server to mongo db.
I don't see that code here.
files server/crop and server/models/crop are the same. I think there is a mistake when you pushed your code.
I'll test the routes once you have added the DB connection code.

**Comment by HixOba** [comment]
Yes, and the reason for that is because i pushed the wrong folder containing files that i am working on to improve my knowledge, as you can see i even failed to push the index.js file which contains the mongoose connection. I have pushed it now so you can look at it while i look to edit and delete the extra two folders.

**Review by yassinej — CHANGES_REQUESTED** [review]
1- remove the server/crop.js useless file
2- remove the line `collections: "crops"`
3- remove the line `const Crop = require("./models/crop");` in index.js

**Comment by HixOba** [comment]
Restarting it

**Pull request closed without merging**
